CinemaTicketWeb/Areas/Admin/Controllers/GenreController.cs
using CinemaTicket.Core.Contracts;
using CinemaTicket.Models;
using CinemaTicket.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CinemaTicketWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class GenreController : Controller
    {
        private readonly IGenreService genreService;

        public GenreController(IGenreService _genreService)
        {
            genreService = _genreService;
        }
        public IActionResult Index()
        {

            return View(genreService.GetAllGenres());
        }

        //Get
        public IActionResult Create()
        {

            return View();
        }

        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Genre obj)
        {
            if (genreService.IfGenreExit(obj))
            {
                ModelState.AddModelError("name", "This genre name exist!");
            }
            if (ModelState.IsValid)
            {
                genreService.AddGenre(obj);

                TempData["success"] = "Genre created successfully";

                return RedirectToAction("Index");
            }


            return View(obj);
        }

        //Get
        public IActionResult Edit(int? id)
        {
            if (id is null or 0)
            {
                return NotFound();
            }
            var genreFromDb = genreService.GetGenre(id);
            if (genreFromDb == null)
            {
                return NotFound();
            }
            return View(genreFromDb);
        }

        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Genre obj)
        {

            if (ModelState.IsValid)
            {
                genreService.UpdateGenre(obj);

                TempData["success"] = "Genre updated successfully";
                return RedirectToAction("Index");
            }


            return View(obj);
        }

        //Get
        public IActionResult Delete(int? id)
        {


            if (id is null or 0)
            {
                return NotFound();
            }

            var genreFromDb = genreService.GetGenre(id);
            if (genreFromDb == null)
            {
                return NotFound();
            }
            return View(genreFromDb);
        }

        //Post
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {


            var obj = genreService.GetGenre(id);
            if (obj == null)
            {
                return NotFound();
            }
            genreService.DeleteGenre(obj);
            TempData["success"] = "Genre deleted successfully";
            return RedirectToAction("Index");

        }
    }
}

CinemaTicketWeb/Areas/Admin/Controllers/TicketController.cs
using CinemaTicket.Core.Contracts;
using CinemaTicket.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using CinemaTicket.Utility;
using Microsoft.AspNetCore.Authorization;

namespace CinemaTicketWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
    public class TicketController : Controller
    {
        private readonly ITicketService ticketService;
        private readonly IWebHostEnvironment _hostEnvironment;

        public TicketController(ITicketService _ticketService, IWebHostEnvironment hostEnvironment)
        {
            ticketService = _ticketService;
            _hostEnvironment = hostEnvironment;
        }
        public IActionResult Index()
        {

            return View();
        }



        //Get
        public IActionResult Upsert(int? id)
        {
            var ticketVM = ticketService.GetTicketVM();

            if (id is null or 0)
            {
                //create ticket
                //ViewBag.CategoryList = CategoryList;
                //ViewData["GenreList"] = GenreList;
                return View(ticketVM);
            }
            else
            {
                //update ticket
                ticketVM.Ticket = ticketService.GetTicketFirst(id);
                return View(ticketVM);
            }


        }

        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(TicketVM obj, IFormFile? file)
        {


            if (ModelState.IsValid)
            {
                string wwwRootPath = _hostEnvironment.WebRootPath;
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(wwwRootPath, @"images\tickets");
                    var extention = Path.GetExtension(file.FileName);

                    if (obj.Ticket.ImageUrl != null)
                    {
                        var oldImagePath = Path.Combine(wwwRootPath, obj
                            .Ticket.ImageUrl.TrimStart('\\'));

                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }
                    using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extention), FileMode.Create))
                    {
                        file.CopyTo(fileStreams);
                    }

                    obj.Ticket.ImageUrl = @"\images\tickets\" + fileName + extention;

                }

                if (obj.Ticket.Id == 0)
                {
                   ticketService.AddTicket(obj,file);
                   TempData["success"] = "Ticket added successfully!";
                }
                else
                {
                    ticketService.UpdateTicket(obj,file);
                    TempData["success"] = "Ticket updated successfully!";
                }


               

               
                return RedirectToAction("Index");
            }


            return View(obj);
        }

        #region API CALLS

        [HttpGet]
        public IActionResult GetAll()
        {
            
            return Json(new { data = ticketService.GetAll() });


        }

        //POST
        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var obj = ticketService.GetTicketFirst(id);
            if (obj == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }

            var oldImagePath = Path.Combine(_hostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
            if (System.IO.File.Exists(oldImagePath))
            {
                System.IO.File.Delete(oldImagePath);
            }

          ticketService.DeleteTicket(obj);
          
            return Json(new { success = true, message = "Delete Successful!" });

        }

        #endregion


    }
}

CinemaTicketWeb/Controllers/CategoryController.cs
using CinemaTicket.Core.Contracts;
using CinemaTicket.Infrastructure.Data;
using CinemaTicket.Models;
using Microsoft.AspNetCore.Mvc;

namespace CinemaTicketWeb.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _db;

        public CategoryController(IUnitOfWork db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Category> objCategoryList = _db.Category.GetAll();
            return View(objCategoryList);
        }
        
        //Get
        public IActionResult Create()
        {
            
            return View();
        } 
        
        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category obj)
        {
            if (_db.Category.GetAll().Any(x=>x.Name == obj.Name))
            {
                ModelState.AddModelError("name", "This category name exist!");
            }
            if (ModelState.IsValid)
            {
                _db.Category.Add(obj);
                _db.Save();

                TempData["success"] = "Category created successfully";

                    return RedirectToAction("Index");
            }


            return View(obj);
        }

        //Get
        public IActionResult Edit(Guid? id)
        {

            if (id == null )
            {
                return NotFound();
            }

            var categoryFromDb = _db.Category.GetFirstOrDefault(u=>u.Id==id);;
            if (categoryFromDb == null)
            {
                return NotFound();
            }
            return View(categoryFromDb);
        }

        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category obj)
        {
           
            if (ModelState.IsValid)
            {
                _db.Category.Update(obj);
                _db.Save();

                TempData["success"] = "Category updated successfully";
                return RedirectToAction("Index");
            }


            return View(obj);
        }

        //Get
        public IActionResult Delete(Guid? id)
        {
            
           
            if (id == null )
            {
                return NotFound();
            }

            var categoryFromDb = _db.Category.GetFirstOrDefault(u=>u.Id==id);
            if (categoryFromDb == null)
            {
                return NotFound();
            }
            return View(categoryFromDb);
        }

        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(Guid? id)
        {


            var obj = _db.Category.GetFirstOrDefault(u=>u.Id==id);
            if (obj == null)
            {
                return NotFound();
            }
                _db.Category.Remove(obj);
                _db.Save();
                TempData["success"] = "Category deleted successfully";
                return RedirectToAction("Index");
            
        }
    }
}

CinemaTicketWeb/ViewComponents/ShoppingCartViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using CinemaTicket.Infrastructure.Data.Repositories.IRepository;
using CinemaTicket.Utility;

namespace CinemaTicketWeb.ViewComponents
{
    public class ShoppingCartViewComponent : ViewComponent
    {
        private readonly IUnitOfWork _unitOfWork;
        public ShoppingCartViewComponent(IUnitOfWork unitOfWork)
        {
            _unitOfWork= unitOfWork;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (claim != null)
            {
                if (HttpContext.Session.GetInt32(SD.SessionCart) != null)
                {
                    return View(HttpContext.Session.GetInt32(SD.SessionCart));
                }
                else
                {
                    HttpContext.Session.SetInt32(SD.SessionCart,
                        _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == claim.Value).ToList().Count);
                    return View(HttpContext.Session.GetInt32(SD.SessionCart));
                }
            }
            else
            {
                HttpContext.Session.Clear();
                return View(0);
            }
        }
    }
}

CinemaTicketWeb/Views/Shared/_Layout.cshtml
@using CinemaTicket.Utility


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieHouse </title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdn.datatables.net/1.11.2/css/jquery.dataTables.min.css" />
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Movie House</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor02">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">

                        <a class="nav-link " asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    @if (User.IsInRole(SD.Role_Admin))
                    {

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Content Managment</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Genre" asp-action="Index">Genre</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Ticket" asp-action="Index">Movie Ticket</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Create User</a>
                            </div>
                        </li>

                    }
                    <li class="nav-item">
                        <a class=nav-link asp-area="Admin" asp-controller="Order" asp-action="Index">
                            Manage Order
                        </a>
                    </li>


                    <li class="nav-item">
                        <a class=nav-link asp-area="Customer" asp-controller="Cart" asp-action="Index">
                            @await Component.InvokeAsync("ShoppingCart")
                        </a>
                    </li>

                </ul>
                <partial name="_LoginPartial"/>
             
            </div>
        </div>
    </nav>
    @*<partial name="_CookieConsentPartial" />*@
</header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification"/>
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted bg-primary">
        <div class="container">
            &copy; @DateTime.Now.Year - MovieHouse - by AR Freelancer
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.11.2/js/jquery.dataTables.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="https://cdn.tiny.cloud/1/n94ifuzvl80pchikopiwgz2esrw8n28dwcywvpejlqrregfp/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CinemaTicketWeb/Views/Shared/_LayoutAdmin.cshtml
@using CinemaTicket.Utility
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css" />
    <link rel="stylesheet" href="~/css/adminlte.min.css" />
    <link rel="stylesheet" href="~/plugins/toastr/toastr.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.11.2/css/jquery.dataTables.min.css" />

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @await RenderSectionAsync("Head", false)
</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">

        <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="/" class="nav-link">Home</a>
      </li>
    </ul>
   
    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      
      <partial name="_LoginPartial"/>
      <!-- Navbar Search -->
     

      <!-- Messages Dropdown Menu -->

      <!-- Notifications Dropdown Menu -->

      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="\" class="brand-link">
      <img src="~/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">Movie House</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="~/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="/Identity/Account/Manage" class="d-block">Admin Panel</a>
        </div>
      </div>

      <!-- SidebarSearch Form -->
      

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
          with font-awesome or any other icon font library -->
          <li class="nav-item menu-open">
            <a href="#" class="nav-link active">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Starter Pages
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              @if (User.IsInRole(SD.Role_Admin))
              { 
                <li class="nav-item">
                  <a class="nav-link active" asp-area="Admin" asp-controller="Category" asp-action="Index"> <i class="far fa-circle nav-icon"></i>Category</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" asp-area="Admin" asp-controller="Genre" asp-action="Index"> <i class="far fa-circle nav-icon"></i>Genre</a>
                </li>

              }
             
              
              <li class="nav-item">
                <a class="nav-link active" asp-area="Admin" asp-controller="Ticket" asp-action="Index"><i class="far fa-circle nav-icon"></i>Movie Ticket</a>
              </li>
            @if (User.IsInRole(SD.Role_Admin))
            {
              <li class="nav-item">
                <a class="nav-link active" asp-area="Admin" asp-controller="Company" asp-action="Index"><i class="far fa-circle nav-icon"></i>Company</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" asp-area="Identity" asp-page="/Account/Register"><i class="far fa-circle nav-icon"></i>Create User</a>
              </li>
            }
              <li class="nav-item">
                <a class=nav-link asp-area="Admin" asp-controller="Order" asp-action="Index"><i class="far fa-circle nav-icon"></i>Manage Order</a>
              </li>
            </ul>
          </li>
         
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
          <partial name="_CookieConsentPartial" />
          <!-- Content Header (Page header) -->
          <div class="content-header">
            <div class="container-fluid">
              <div class="row mb-2">
                <div class="col-sm-6">
                  <h1 class="m-0">Starter Page</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                  <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="\">Home</a></li>
                    <li class="breadcrumb-item active">Starter Page</li>
                  </ol>
                </div><!-- /.col -->
              </div><!-- /.row -->
            </div><!-- /.container-fluid -->
          </div>
          <!-- /.content-header -->

          <!-- Main content -->
          <div class="content">
            <div class="container-fluid">
              @RenderBody()
            </div><!-- /.container-fluid -->

          </div>
          <!-- /.content -->
        </div>
  <!-- /.content-wrapper -->

  <!-- Control Sidebar -->
 @* <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
    <div class="p-3">
      <h5>Title</h5>
      <p>Sidebar content</p>
    </div>
  </aside>*@
  <!-- /.control-sidebar -->

        <!-- Main Footer -->
        <footer class="main-footer">
            <!-- To the right -->
            <div class="float-right d-none d-sm-inline">
                Anything you want
            </div>
            <!-- Default to the left -->
            <strong>Copyright &copy; 2014-@DateTime.Now.Year <a href="/">MovieHouse</a>.</strong> All rights reserved.
        </footer>
    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED SCRIPTS -->
    <!-- jQuery -->
    <script src="~/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/js/adminlte.min.js"></script>
    <script src="~/plugins/toastr/toastr.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.11.2/js/jquery.dataTables.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="https://cdn.tiny.cloud/1/n94ifuzvl80pchikopiwgz2esrw8n28dwcywvpejlqrregfp/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <partial name="_Notification" />
    @await RenderSectionAsync("Scripts", false)
</body>
</html>

CinemaTicketWeb/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if(TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}