CinemaTicketWeb/Areas/Admin/Controllers/CompanyController.cs
using CinemaTicket.Core.Contracts;
using CinemaTicket.Models;
using CinemaTicket.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CinemaTicketWeb.Areas.Admin.Controllers;
[Area("Admin")]
[Authorize(Roles = SD.Role_Admin)]
public class CompanyController : Controller
{
    private readonly ICompanyService companyService;

    public CompanyController(ICompanyService _companyService)
    {
       companyService = _companyService;
    }

    public IActionResult Index()
    {
        return View();
    }

    //GET
    public IActionResult Upsert(int? id)
    {
        Company company = new();

        if (id is null or 0)
        {
            return View(company);
        }
        else
        {
            company = companyService.GetCompany(id);
            return View(company);
        }
    }

    //POST
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Upsert(Company obj, IFormFile? file)
    {

        if (ModelState.IsValid)
        {
            
            if (obj.Id == 0)
            {
                companyService.AddCompany(obj,file);
                TempData["success"] = "Company created successfully";
            }
            else
            {
                companyService.UpdateCompany(obj,file);
                TempData["success"] = "Company updated successfully";
            }
            
            
            return RedirectToAction("Index");
        }
        return View(obj);
    }

    #region API CALLS
    [HttpGet]
    public IActionResult GetAll()
    {
        var companyList = companyService.GetAllCompanies();
        return Json(new { data = companyList });
    }

    //POST
    [HttpDelete]
    public IActionResult Delete(int? id)
    {
        var obj = companyService.GetCompany(id);
        if (obj == null)
        {
            return Json(new { success = false, message = "Error while deleting" });
        }

        companyService.DeleteCompany(obj);
        return Json(new { success = true, message = "Delete Successful" });

    }
    #endregion
}

CinemaTicketWeb/Areas/Admin/Views/Company/Index.cshtml
<div class="container p-3">
	<div class="row pt-4">
		<div class="col-6">
			<h2 class="text-primary">Company List</h2>
		</div>
		<div class="col-6 text-end">
			<a asp-controller="Company" asp-action="Upsert" class="btn btn-primary">
				<i class="bi bi-plus-circle"></i> &nbsp; Create New Company
			</a>
		</div>
	</div>
	<br /><br />

	<table id="tblData" class="table table-bordered table-striped" style="width:100%">
		<thead>
			<tr>
				<th>Name</th>
				<th>Address</th>
				<th>City</th>
				<th>State</th>
				<th>Phone Number</th>
				<th></th>
			</tr>
		</thead>
	</table>
</div>

@section Scripts{
<script src="~/js/company.js"></script>
}

CinemaTicketWeb/Areas/Admin/Views/Company/Upsert.cshtml
@model Company

<form method="post" asp-action="Upsert" enctype="multipart/form-data">
	<input asp-for="Id" hidden />
	
	<div class="row">
		<div class="col-10">
			<div class="border p-3 mt-4 row">
		<div class="col-12 pb-2">
			<h2 class="text-primary">@(Model.Id!=0?"Update": "Create")  Company</h2>
			<hr />
		</div>
		@*<div asp-validation-summary="All"></div>*@
		<div class="mb-3">
			<label asp-for="Name"></label>
			<input asp-for="Name" class="form-control" />
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="PhoneNumber"></label>
			<input asp-for="PhoneNumber" class="form-control" />
			<span asp-validation-for="PhoneNumber" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="StreetAddress"></label>
			<input asp-for="StreetAddress" class="form-control" />
			<span asp-validation-for="StreetAddress" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="City"></label>
			<input asp-for="City" class="form-control" />
			<span asp-validation-for="City" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="State"></label>
			<input asp-for="State" class="form-control" />
			<span asp-validation-for="State" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="PostalCode"></label>
			<input asp-for="PostalCode" class="form-control" />
			<span asp-validation-for="PostalCode" class="text-danger"></span>
		</div>
		
		<div class="col-12">
			@if (Model.Id != 0)
			{
				<button type="submit" class="btn btn-primary" style="width:150px">Update</button>
			}
			else
			{
				<button type="submit" class="btn btn-primary" style="width:150px">Create</button>
			}
			<a asp-controller="Company" asp-action="Index" class="btn btn-secondary" style="width:150px">
				Back to List
			</a>
		</div>

	</div>
		</div>
		
	</div>
</form>

@section Scripts{
	@{
	<partial name="_ValidationScriptsPartial" />
	}
}